stack_identifiers:
  priorities:
    "wolfyutilities:helixitems": 2100
    "wolfyutilities:mmoitems": 2000
    "wolfyutilities:oraxen": 1900
    "wolfyutilities:mythicmobs": 1600
    "wolfyutilities:itemsadder": 1500
    "wolfyutilities:eco": 100
    "wolfyutilities:denizen": 0
    "wolfyutilities:wolfyutils": 0
    # Make sure the bukkit identifier has the lowest priority at all times! This will otherwise overwrite everything
    "wolfyutilities:bukkit": -4096
